apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: mongo-express:1.0.0-20-alpine3.17
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-cred
                key: MONGO_USER

          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-cred
                key: MONGO_PASSWORD
          
          - name: ME_CONFIG_MONGODB_SERVER        
            valueFrom:
              configMapKeyRef:
                key: mongo-url
                name: mongo-config

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30007

